### ISSUE TITLE
Bug: Download button not working due to Udemy class name changes.

### ISSUE THREAD

**Issue by theorib** [CuriousAlways/udemy-notes-downloader#1]
Hi, thanks for building this extension, I've been looking everywhere for something like this.
Unfortunately I can't seem to get it to work.

I am running Chrome Version 123.0.6312.87 (Official Build) (arm64) on a mac.
Mostly I get the following alert: `No notes found!!! plz ensure your are on udemy course notes tab.`
I tried different configurations like changing the code formatting language or not setting one as well as the other checkbox options.

I am running the extension on the notes tab of a course but the extension can't find the notes.
I'd be happy to share any more relevant information you may need and to contribute in any way I can.

When I inspect Udemy's page HTML, the container that has all the notes has a:
`data-purpose="bookmarks-container"` attribute
`class="bookmarks--bookmarks--2bSvq" ` class
Every note is wrapped in a `class="lecture-bookmark-v2--bookmark-container--KXG59"`

A screenshot of the error:
![Screenshot 2024-03-29 at 10 07 41](https://github.com/CuriousAlways/udemy-notes-downloader/assets/10909928/3c0b3a3a-39a1-4481-b3d0-f3206fa81492)

The current markup for the notes:
![Screenshot 2024-03-29 at 10 18 47](https://github.com/CuriousAlways/udemy-notes-downloader/assets/10909928/30d0c150-c272-4921-a2a0-b15e5df8ff11)

These are my extension configurations:
![Screenshot 2024-03-29 at 10 12 29](https://github.com/CuriousAlways/udemy-notes-downloader/assets/10909928/2c85e782-834c-474b-958a-669f94ac7896)

**Comment by theorib** [comment]
Just a quick follow up:
When I inspect Udemys HTML on my browser, every note is wrapped in a `class="lecture-bookmark-v2--bookmark-container--KXG59"`

I've noticed that on this projects `udemy-notes-downloader/src/contentScript.js` the class defined for the `ENCLOSING_ELEMENT_SELECTOR` constant is `lecture-bookmark-v2--content-container--2f_Tg`

I'm not sure if Udemy changes the last five characters of the classname for every user or perhaps every once in a while but that seems to be the possible source for this issue.

**Comment by CuriousAlways** [comment]
@theorib  thanks for raising the issue,  been busy with the work lately. I'll try to raise to fix the issue this weekend or if u like plz raise a pr

**Comment by theorib** [comment]
Thanks for getting back @CuriousAlways ! I will give it a go. This would be my first pr ever :) 
I've just cloned the project and after changing the constant `ENCLOSING_ELEMENT_SELECTOR` to the class I have here  in my browser (`lecture-bookmark-v2--content-container--hoogx`) and that did the trick.  The extension is now working.

I'll have a think about how I could make that class dynamic in the codebase to accommodate this kind of stuff and then raise a PR.
